# Generated by Django 2.1.4 on 2018-12-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('longit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('build_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Building')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ist_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('range_user', models.IntegerField()),
                ('lat', models.FloatField()),
                ('longit', models.FloatField()),
                ('build_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Building')),
            ],
        ),
    ]
