# Generated by Django 2.1.4 on 2018-12-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='building',
            name='longit',
        ),
    ]
