# Generated by Django 2.1.4 on 2019-01-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsMovements',
            fields=[
                ('ist_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('build_id', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
